package restaurant.dao.repositories.impl;

import restaurant.dao.repositories.IMenuRepository;
import restaurant.domain.Menu;
import restaurant.dao.mappers.*;
import restaurant.dao.uow.*;

import java.sql.Connection;
import java.sql.SQLException;
import java.util.List;

public class MenuRepository extends RepositoryBase<Menu> implements IMenuRepository {

    public MenuRepository(Connection connection, IMapper<Menu> mapper, IUnitOfWork uow) throws SQLException {
        super(connection, mapper, uow);
    }

    @Override
    protected String createTableSql() {
        return "CREATE TABLE IF NOT EXISTS menu("
                + "id bigint GENERATED BY DEFAULT AS IDENTITY,"
                + "restaurantId bigint,"
                + "menuType VARCHAR(64),"
                + ")";
    }

    @Override
    protected String getTableName() {
        return "menu";
    }

    @Override
    protected String getUpdateSql() {
        return "UPDATE menu SET (restaurantId, menuType)=(?,?) WHERE id=?";
    }

    @Override
    protected String getInsertSql() {
        return "INSERT INTO menu(restaurantId,menuType) VALUES(?,?)";
    }

    @Override
    protected void setInsert(Menu menu) throws SQLException {
        insert.setInt(1, menu.getRestaurantId());
        insert.setString(2, menu.getMenuType());
    }

    @Override
    protected void setUpdate(Menu menu) throws SQLException {
        update.setInt(1, menu.getRestaurantId());
        update.setString(2, menu.getMenuType());
    }

    public List<Menu> withMenuId(int id) {
        return null;
    }

    public List<Menu> withRestaurantId(int id) {
        return null;
    }

    public List<Menu> withMenuType(String surname) {
        return null;
    }

}
